# ==========================
# GitHub Pages Configuration
# ==========================
title: "BuilderGPT"
description: "rá»£ lÃ½ Ká»¹ Thuáº­t láº­p trÃ¬nh cho ngÆ°á»i Viá»‡t lÃ  má»™t GPT tÃ¹y chá»‰nh Ä‘Æ°á»£c thiáº¿t káº¿ Ä‘á»ƒ há»— trá»£ cÃ¡c láº­p trÃ¬nh viÃªn vÃ  ká»¹ sÆ° pháº§n má»m Viá»‡t Nam phÃ¡t triá»ƒn dá»± Ã¡n theo quy trÃ¬nh hiá»‡n Ä‘áº¡i má»™t cÃ¡ch tá»± Ä‘á»™ng vÃ  dá»… dÃ ng hÆ¡n."

theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag

# author:
#   name: "Nguyá»…n PhÆ°á»›c Thuáº­n"
#   email: "thuannp.hcmc@gmail.com"
#   github: "ThuanNP"
#   url: "https://thuannp.github.io/chatgpt-tech-builder-for-vietnamese"

author: "Â© Nguyá»…n PhÆ°á»›c Thuáº­n"

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://github.com/ThuanNP"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/nguyenphuocthuan"
    - platform: globe
      user_url: "https://techbuilder.vn"

# ğŸ”— Chá»‰ liá»‡t kÃª TRANG CON cáº§n hiá»‡n trÃªn menu
header_pages:
  - index.md
  - privacy-policy.md
  - terms-of-service.md

# ğŸš€ Project Pages: cáº¥u hÃ¬nh ÄÃšNG cho URL
url: "https://thuannp.github.io"
baseurl: "/chatgpt-tech-builder-for-vietnamese"

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
